### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by karldreher** [karldreher/x-men-cards#7]
CSS style below, for a rainy day.

As it stands this is too "pulp Fiction" and not quite "X-Men".

```css

.x-title { 
	font-size: 120;
    perspective: 200px;
    transform: skewX(200deg) rotate3d(10deg,3,180,1deg);
    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
    font-variant: small-caps;
    color: yellow;
	text-shadow:0 .01em 0px red,
		0 .015em 0 red,
		0 .02em  0 red,
		0 .028em 0 red,
		0 .035em 0 red,
		0 .04em  0 red,
		0 .045em 0 red,
		0 .055em 0 red,
		0 .06em  0 red,
		0 .065em 0 red,
		0 .07em  0 darkred,
		0 .08em  0 darkred,
		0 .085em 0 black,
		0 .09em  0 black,
		0 .095em 0 black,
		0 .105em 0 black,
		0 .06em .06rem rgba(104, 104, 92, 0.15),
		.07em .105em .04em rgba(0, 0, 0, .015),
		-.02em .09em .05em rgba(104, 104, 92, 0.25),
		-.03em .07em .065em rgba(104, 104, 92, 0.1),
		-.075em .08em .09em rgba(104, 104, 92, 0.06),
		-.09em .06em .195em rgba(104, 104, 92, 0.095);
}
```
